# very simple makefile
# top down 

main_CSE241_161044007:
	javac main_CSE241_161044007.java  Collection.java List.java Set.java Queue.java Iterator.java LinkedList.java HashSet.java ArrayList.java

run : 
	java main_CSE241_161044007

clean:
	rm *.class


